/** Convert assets/icons-src/*.svg to PNGs and a base64 data-URL module. */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, join } from "node:path"
import { Resvg } from "@resvg/resvg-js"

const ROOT = new URL("..", import.meta.url).pathname
const SRC = join(ROOT, "assets", "icons-src")
const OUT = join(ROOT, "assets", "icons")
const MODULE = join(ROOT, "src", "assets-icons.ts")

mkdirSync(OUT, { recursive: true })
const entries = {}
for (const file of readdirSync(SRC).filter((f) => f.endsWith(".svg")).sort()) {
  const name = basename(file, ".svg")
  const raw = readFileSync(join(SRC, file), "utf8")
  const svg = raw.includes("xmlns=") ? raw : raw.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"')
  const png = new Resvg(svg, { fitTo: { mode: "width", value: 64 } }).render().asPng()
  writeFileSync(join(OUT, `${name}.png`), png)
  entries[name] = `data:image/png;base64,${png.toString("base64")}`
}

const lines = Object.entries(entries).map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
writeFileSync(MODULE, `// Generated by scripts/icons.mjs — do not edit.\nexport const TOOL_ICON_PNG: Record<string, string> = {\n${lines.join("\n")}\n}\n`)
console.log(`wrote ${Object.keys(entries).length} icons -> assets/icons/*.png + src/assets-icons.ts`)
